# Generated by Django 5.0.3 on 2024-03-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pic',
            new_name='profile_Picture',
        ),
    ]
